# --- navigation ---
# plugin: smart-paste.yazi
[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]] # cd back to the root of the current Git repository (from yazi tips)
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "cd back to the root of the current git repo"

[[mgr.prepend_keymap]]
on = [ "g", "d" ]
run = "cd ~/dotfiles"

[[mgr.prepend_keymap]]
on = [ "g", "D" ]
run = "cd ~/Downloads"

[[mgr.prepend_keymap]]
on = [ "g", "P" ]
run = "cd ~/Projects"

# --- view ---
## plugin: toggle-pane
[[mgr.prepend_keymap]]
on   = "H"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"
[[mgr.prepend_keymap]]
on   = "M"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

# --- edit ---
[[input.prepend_keymap]] # from yazi tips
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

